config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands
  resources :albums, :tracks, except: [:index]
  resources :notes, only: [:create, :destroy]
  get "activation/:id" => "users#activate"
end

app/models/note.rb
class Note < ApplicationRecord
  validates :user_id, :track_id, :body, presence: true

  belongs_to :user
  belongs_to :track
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id
    if @note.save
      redirect_to track_url(@note.track_id)
    else
      flash[:errors] = ["You done goofed"]
      redirect_to track_url(@note.track_id)
    end
  end

  def destroy
    @note = Note.find_by(id: params[:id])

    if @note && (@note.user_id == current_user.id || current_user.admin_status)
      @note.destroy
      redirect_to track_url(@note.track_id)
    else
      flash[:errors] = ["janked up the server"]
      render text: "GET OUT BRUH", status: :forbidden
    end
  end

  private

  def note_params
    params.require(:note).permit(:body, :track_id)
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<form action="<%= notes_url %>" method="post">
  <%= auth_token %>

  <textarea name="note[body]" rows="8" cols="80"></textarea>
  <input type="hidden" name="note[track_id]" value="<%=track.id%>">
  <input type="submit">
</form>

app/views/notes/_note.html.erb
<h4><%= note.user.email %></h4> <%=(link_to "Delete Note", note_url(note), method: :delete) if current_user.id == note.user_id || current_user.admin_status %>
<h5> _______________________________________________________________</h5>
<p> <%= note.body %> </p>
<h5> _______________________________________________________________</h5>