config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands
  resources :albums, :tracks, except: [:index]
  resources :notes, only: [:create, :destroy]
  get "activation/:id" => "users#activate"
end

app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  album_id   :integer          not null
#  bonus      :boolean          default("false")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Track < ApplicationRecord
  validates :album_id, :name, presence: true
  validates :bonus, inclusion: [true, false]

  has_many :notes,
    dependent: :destroy

  belongs_to :album
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :require_login

  def new
    @track = Track.new
    render :new
  end

  def show
    @track = Track.find_by(id: params[:id])
    render :show
  end

  def create
    @track = Track.new(track_params)

    if @track.save
      redirect_to track_url(@track)
    else
      flash[:errors] = ['Invalid track! Bogus.....']
      redirect_to new_track_url
    end
  end

  def edit
    @track = Track.find_by(id: params[:id])
    render :edit
  end

  def update
    @track = Track.find_by(id: params[:id])

    if @track.update_attributes(track_params)
      redirect_to track_url
    else
      flash[:errors] = ['Invalid track! Bogus.....']
      redirect_to new_track_url
    end
  end

  def destroy
    @track = Track.find_by(id: params[:id])

    if @track
      @track.destroy
      redirect_to bands_url
    else
      flash[:errors] = ['Track does not exist']
      redirect_to bands_url
    end
  end

  private

  def track_params
    params.require(:track).permit(:name, :album_id, :bonus, :lyrics)
  end
end

app/helpers/tracks_helper.rb
module TracksHelper

  def ugly_lyrics(lyrics)
    "♫ " + lyrics.split("\n").join("\n♫ ")
  end

end

app/views/tracks/_form.html.erb
<% albums = Album.all %>
<% if action == :new %>
  <% action_url = tracks_url %>
<% elsif action == :edit %>
  <% action_url = track_url %>
<% end %>
<form action="<%= action_url %>" method="post">
  <%= auth_token %>
  <% if action == :edit %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>
  <label for="track">Track Name</label>
  <br>
  <input id="track" type="text" name="track[name]" value="<%=track.name%>">

  <br>

  <label for="album">Album</label>
  <br>
  <select id="album" name="track[album_id]">
    <option disabled selected>--Please Select Album--</option>
      <% albums.each do |album|%>
        <option <%= track.album_id == album.id ? "selected" : "" %> value="<%= album.id %>"><%= album.name %></option>
      <% end %>
  </select>

  <br>
  <label for="track_type">Track Type</label>
  <br>

  Bonus<input <%=track.bonus ? "checked" : ""%> type="radio" name="track[bonus]" value="true">
  Regular<input <%=track.bonus ? "" : "checked"%> type="radio" name="track[bonus]" value="false">


  <br>
  <label for="lyrics">Lyrics</label>
  <br>
  <textarea id="lyrics" name="track[lyrics]" rows="8" cols="80"><%=track.lyrics%></textarea>

  <br>

  <input type="submit">

app/views/tracks/edit.html.erb
<%= render "form", action: :edit, track: @track %>

app/views/tracks/new.html.erb
<%= render "form", action: :new, track: @track %>

app/views/tracks/show.html.erb
<% track = Track.includes(:album).find_by(id: params[:id]) %>

<br>

<%= link_to "Back to Album", album_url(track.album) %>

<br>

<h1><%= track.name %></h1>
<% if current_user.admin_status %>
  <%= link_to "Edit", edit_track_url(track) %>
  <%= link_to "Delete", track_url(track), method: :delete %>
<% end %>
<h3><%= track.album.name %></h3>
<h4> <%= "Bonus Track" if track.bonus %> </h4>
<br>
</br>
<h3>Lyrics:</h3>
<p> <pre><%= ugly_lyrics(track.lyrics) %></pre> </p>
<% @note = track.notes %>

<h2>Notes:</h2>
<%= render @note %>
<%= render "notes/form", track: track%>