config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands
  resources :albums, :tracks, except: [:index]
  resources :notes, only: [:create, :destroy]
  get "activation/:id" => "users#activate"
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  band_id    :integer          not null
#  name       :string           not null
#  genre      :string
#  album_type :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ApplicationRecord
  validates :name, :band_id, presence: true
  validates :album_type, inclusion: ['studio', 'live', nil]

  has_many :tracks,
    dependent: :destroy
    
  belongs_to :band
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :require_login

  def new
    @album = Album.new
    render :new
  end

  def show
    @album = Album.find_by(id: params[:id])
    render :show
  end

  def create
    @album = Album.new(album_params)

    if @album.save
      redirect_to album_url(@album)
    else
      flash[:errors] = ['Invalid album! Bogus.....']
      redirect_to new_album_url
    end
  end

  def edit
    @album = Album.find_by(id: params[:id])
    render :edit
  end

  def update
    @album = Album.find_by(id: params[:id])

    if @album.update_attributes(album_params)
      redirect_to album_url
    else
      flash[:errors] = ['Invalid album! Bogus.....']
      redirect_to new_album_url
    end
  end

  def destroy
    @album = Album.find_by(id: params[:id])

    if @album
      @album.destroy
      redirect_to bands_url
    else
      flash[:errors] = ['Album does not exist']
      redirect_to bands_url
    end
  end

  private

  def album_params
    params.require(:album).permit(:name, :band_id, :genre, :album_type)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<% bands = Band.all %>

<% if action == :edit %>
  <% action_url = album_url %>
<% elsif action == :new %>
  <% action_url = albums_url %>
<% end %>

<form action="<%= action_url %>" method="post">
  <%= auth_token %>

  <% if action == :edit %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>

  <label for="album">Album Name</label>
  <br>
  <input id="album" type="text" name="album[name]" value="<%= album.name %>">

  <br>

  <label for="band">Band</label>
  <br>
  <select id="band" name="album[band_id]">
    <option disabled selected>--Please Select Band--</option>
      <% bands.each do |band|%>
        <option <%= album.band_id == band.id ? "selected" : "" %> value="<%= band.id %>"><%= band.name %></option>
      <% end %>
  </select>

  <br>
  <label for="album_type">Album Type</label>
  <br>

  Live<input <%= album.album_type == "live" ? "checked" : "" %> type="radio" name="album[album_type]" value="live">
  Studio<input <%= album.album_type == "studio" ? "checked" : "" %> type="radio" name="album[album_type]" value="studio">


  <br>

  <input type="submit">
</form>

app/views/albums/edit.html.erb
<%= render 'form', action: :edit, album: @album %>

app/views/albums/new.html.erb
<%= render "form", action: :new, album: @album %>

app/views/albums/show.html.erb
<% album = Album.includes(:tracks).includes(:band).find_by(id: params[:id]) %>
<% tracks = album.tracks %>

<%= link_to "Back to Band", band_url(album.band) %>

<h1><%=album.name%></h1>
<% if current_user.admin_status %>
  <%= link_to "Edit", edit_album_url(album) %>
  <%= link_to "Delete", album_url(album), method: :delete %>
<% end %>

<br>
<h2>Tracks</h2>
<ul>
  <% if tracks.empty? %>
    <h3>No tracks....</h3>
  <%else%>
  <% tracks.each do |track| %>
    <li><%= link_to "#{track.name}", track_url(track) %><%= button_to 'Edit', edit_track_url(track), method: :get%> </li>
    <% end %>
  <% end %>
</ul>

<%= link_to "New Track", new_track_url%>