config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands
  resources :albums, :tracks, except: [:index]
  resources :notes, only: [:create, :destroy]
  get "activation/:id" => "users#activate"
end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true
  has_many :albums,
    dependent: :destroy

  has_many :tracks,
    through: :albums,
    source: :tracks
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :require_login

  def new
    @band = Band.new
    render :new
  end

  def index
    render :index
  end

  def show
    @band = Band.find_by(id: params[:id])
    render :show
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to bands_url
    else
      flash[:errors] = ['Invalid band! Bogus.....']
      redirect_to new_band_url
    end
  end

  def edit
    @band = Band.find_by(id: params[:id])
    render :edit
  end

  def update
    @band = Band.find_by(id: params[:id])

    if @band.update_attributes(band_params)
      redirect_to band_url(@band)
    else
      flash[:errors] = ['Invalid band! Bogus.....']
      redirect_to new_band_url
    end
  end

  def destroy
    @band = Band.find_by(id: params[:id])

    if @band
      @band.destroy
      redirect_to bands_url
    else
      flash[:errors] = ['Band does not exist']
      redirect_to bands_url
    end
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/_form.html.erb
<% if action == :new %>
  <% action_url = bands_url %>
<% elsif action == :edit %>
  <% action_url = band_url %>
<% end %>

<form action="<%= action_url %>" method="post">
  <%= auth_token %>
  <% if action == :edit %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>

  <label for="band">Band Name</label>
  <input id="band" type="text" name="band[name]" value="<%= band.name %>">

  <input type="submit">
</form>

app/views/bands/edit.html.erb
<%= render 'form', action: :edit, band: @band %>

app/views/bands/index.html.erb
<h1>BANDS!!!!!!!!</h1>

<% bands = Band.all %>

<ul>
  <% bands.each do |band| %>
    <li><%= link_to "#{band.name}", band_url(band) %></li>
  <% end %>
</ul>

<%= link_to "New Band", new_band_url%>

app/views/bands/new.html.erb
<%= render 'form', action: :new, band: @band %>

app/views/bands/show.html.erb
<% band = Band.includes(:albums).find_by(id: params[:id]) %>
<% albums = band.albums %>

<%= link_to "Back to Index", bands_url %>

<h1><%= band.name %></h1>
<% if current_user.admin_status %>
  <%= link_to "Edit", edit_band_url(band) %>
  <%= link_to "Delete", band_url(band), method: :delete %>
<% end %>

<h2>Albums</h2>
<ul>
  <% if albums.empty? %>
    <h3>No Albums....</h3>
  <%else%>
  <% albums.each do |album| %>
    <li><%= link_to "#{album.name}", album_url(album) %> <%= button_to "edit", edit_album_url(album), method: :get%> </li>
    <% end %>
  <% end %>
</ul>

<%= link_to "New Album", new_album_url%>